publish_to: none
version: 0.0.0

name: cascade_clearance
description: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Thin.ttf
        weight: 100
      - asset: fonts/Roboto-ThinItalic.ttf
        style: italic
        weight: 100
      - asset: fonts/Roboto-Light.ttf
        weight: 300
      - asset: fonts/Roboto-LightItalic.ttf
        style: italic
        weight: 300
      - asset: fonts/Roboto-Regular.ttf
        weight: 400
      - asset: fonts/Roboto-Italic.ttf
        style: italic
        weight: 400
      - asset: fonts/Roboto-Medium.ttf
        weight: 500
      - asset: fonts/Roboto-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: fonts/Roboto-Bold.ttf
        weight: 700
      - asset: fonts/Roboto-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: fonts/Roboto-Black.ttf
        weight: 900
      - asset: fonts/Roboto-BlackItalic.ttf
        style: italic
        weight: 900